# Generated by Django 3.2 on 2021-05-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='portfolio',
            table='portfolio',
        ),
    ]
