# Generated by Django 3.2 on 2021-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_alter_portfolio_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
