# Generated by Django 3.2 on 2021-06-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_alter_portfolio_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_trackers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_or_dir_name', models.CharField(max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updating', models.BooleanField(default=False)),
            ],
        ),
    ]
