# Generated by Django 3.2 on 2021-07-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_update_trackers'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='delivery_avg_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='update_trackers',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
