# Generated by Django 3.2 on 2021-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='worker_tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_data_at', models.DateTimeField(auto_now=True)),
                ('updated_db_at', models.DateTimeField(auto_now=True)),
                ('updated_charts_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
