# Generated by Django 3.2 on 2021-05-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_worker_tracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_tracker',
            name='downloaded_data_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='updated_charts_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='worker_tracker',
            name='updated_db_at',
            field=models.DateTimeField(),
        ),
    ]
