# Generated by Django 3.2 on 2021-05-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20210527_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_tracker',
            name='instance',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
