# Generated by Django 3.2 on 2021-05-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_worker_tracker_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker_tracker',
            old_name='downloaded_data_at',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='worker_tracker',
            name='updated_charts_at',
        ),
        migrations.RemoveField(
            model_name='worker_tracker',
            name='updated_db_at',
        ),
        migrations.AddField(
            model_name='worker_tracker',
            name='running',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
