# Generated by Django 3.2 on 2021-05-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_auto_20210527_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_tracker',
            name='started_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
