# Generated by Django 3.2 on 2021-05-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_rename_running_worker_tracker_running_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker_tracker',
            old_name='started_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='worker_tracker',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='worker_tracker',
            name='running_status',
        ),
        migrations.AddField(
            model_name='worker_tracker',
            name='file_or_dir_name',
            field=models.CharField(default='default', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker_tracker',
            name='updating',
            field=models.BooleanField(default=False),
        ),
    ]
