# Generated by Django 3.2 on 2021-05-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_test',
            fields=[
                ('ticker', models.CharField(choices=[], max_length=200, primary_key=True, serialize=False)),
                ('owned', models.BooleanField()),
                ('no_of_shares', models.IntegerField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_date', models.DateField()),
                ('amt_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_val', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gain_or_loss', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
